### ISSUE TITLE
various minor typos

### ISSUE THREAD

**Issue by Lianta** [koalaverse/homlr#19]
version **2019-10-19**

### **3.3.1**  
Final paragraph reads

> Perhaps the values were never recoded

should it be "recorded"?

### **4.2.1**
discrepancy in Residual standard error/RMSE of model1 reported. 55750 vs 55753.45

> summary(model1) 
>  \## Residual standard error: 55750 on 2052 degrees of freedom

> sigma(model1)    # RMSE
> \## [1] 55753.45

### **5.3**  
2nd para reads 

> In the background glm() , uses ML estimation

seems to be a comma (and space?) not required

### **6.3**
2nd code chunk comment says:
> \# Apply ridge regression to attrition data

I believe this should be the Ames data

**Comment by bradleyboehmke** [comment]
Thanks for reporting the typos; they have been resolved in the [online version](https://bradleyboehmke.github.io/HOML/). 

Regarding the discrepency in reported residual standard error.  The `summary()` print statement does some rounding to its output for readability purposes; however, the underlying value is not different. For example, here is the same model (but with a different set.seed). Note how the actual sigma values are the same but the print out from summary rounds the value:

```r
summary(model1)

Call:
lm(formula = Sale_Price ~ Gr_Liv_Area, data = ames_train)

Residuals:
    Min      1Q  Median      3Q     Max 
-361143  -30668   -2449   22838  331357 

Coefficients:
            Estimate Std. Error t value            Pr(>|t|)    
(Intercept) 8732.938   3996.613   2.185               0.029 *  
Gr_Liv_Area  114.876      2.531  45.385 <0.0000000000000002 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 56700 on 2051 degrees of freedom
Multiple R-squared:  0.5011,	Adjusted R-squared:  0.5008 
F-statistic:  2060 on 1 and 2051 DF,  p-value: < 0.00000000000000022

> summary(model1)$sigma
[1] 56704.78
> sigma(model1)
[1] 56704.78
```
