### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by DesmondChoy** [koalaverse/homlr#20]
I'm relatively new to GBM but I'm wondering if this is a typo?

**[12.2.1] Sequential training with respect to errors**

Should Step 5 be instead read as:
5. Add this new tree to our algorithm:  

> F3(x) = F2(x) + h2(x)

 ?

Other slight typos:
**[3.3.2.1] Estimated Statistic**
The data output for ```ames_recipe %>% step_medianimpute(Gr_Liv_Area) ``` shouldn't read 

> Box-Cox transformation on all_outcomes()

Instead, it should read 

> Log transformation on all_outcomes()

 as ```ames_recipe``` was last defined as 
```
ames_recipe <- recipe(Sale_Price ~ ., data = ames_train) %>%
  step_log(all_outcomes())
```

**[3.4] Feature Filtering**
Library needed for ```rownames_to_column()``` (tibble::) was not loaded in prior code. I had to use `library(tidyverse)` to run ```rownames_to_column()```

**Comment by bradleyboehmke** [comment]
Thanks @DesmondChoy!  Thanks for reporting the typos; they have been resolved in the [online version](https://bradleyboehmke.github.io/HOML/).
