### ISSUE TITLE
Convert chapters to RStudio Cloud notebooks for interactive use

### ISSUE THREAD

**Issue by bradleyboehmke** [koalaverse/homlr#22]
I'm adding notebooks for each chapter to a [homlr RStudio Cloud project](https://rstudio.cloud/project/801185). This will allow people to run the code chunks (and reproduce figures/tables) for each chapter. 

**Question**: Do we only put the code blocks in the notebook or should we dump the entire chapter into each notebook?  Reference notebooks 02-modeling-process for example of just code chunks and 03-feature-engineering for example of the entire chapter.

If we put in the entire chapter I think we need to add a copyright issue at the bottom. Also, we won't be able to get everything to render properly unless we can get notebooks to leverage the additional css files.  But even then, chapter cross links won't persist.

Thoughts @bgreenwell?

**Comment by bgreenwell** [comment]
We'd probably have to get permission from CRC to dump the entire notebook. I think `02-modeling-process.Rmd` is perfect; it's allows for reproducibility of the output. We can also keep these up to date with changes in R and other packages to make updating the book easier in the future too.

**Comment by bgreenwell** [comment]
Is 1Gb enough RAM to run most of the examples? Should we also include the rendered HTML output on the main site in Supplementary Material (or reserve this for other content)?

**Comment by bradleyboehmke** [comment]
@bgreenwell, unfortunately the 1GB is not enough but I am still adding the notebooks to the RStudio Cloud instance and just making a note of which code chunks (or entire notebooks) should not be ran in RStudio Cloud.
