### ISSUE TITLE
Have you considered assigning an MIT-type license for the book?

### ISSUE THREAD

**Issue by davidkane9** [koalaverse/homlr#23]
Similar to what was done with [Modern Dive](https://moderndive.com/), which uses a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

**Comment by bradleyboehmke** [comment]
Yeah, unfortunately, we didn't think about that ahead of time so it wasn't in the initial contract with CRC Press. All the additional content we are building out (https://koalaverse.github.io/homlr/) will be  CC BY 4.0 licensed but we have to wait 12 months before we can do the same with the book.
