### ISSUE TITLE
chapter 5, possible issue in odds / marginal effect discussion

### ISSUE THREAD

**Issue by cunningjames** [koalaverse/homlr#6]
Book version: 2019-05-25

Section 5.2 "Thus, for every one dollar increase in MonthlyIncome, the odds of an employee attriting decreases slightly, represented by a slightly less than 50% probability." 

I'm not sure this or the code following it works. Since a logit model is nonlinear, the change in probability will depend on where in the support of MonthlyIncome we're looking. The 0.499 figure is a transformation of the coefficient for MonthlyIncome, but I'm not sure this is meaningful because it doesn't include the constant. It could be that my stubborn refusal to view binary classification in terms of odds is leading me astray here, though.

This is related to an issue in section 5.4: ""however, working OverTime tends to nearly double the probability of attrition."

I may not understand. But from a monthly income of 1000, model3 would indicate that working raises the probability of attrition by about 2.75 times. 

    pred_prob <- function(ot) {
      predict(model3, tibble(MonthlyIncome = 1000, OverTime = ot), type = "response")
    }
    pred_prob("Yes") / pred_prob("No")  # => 2.75488

**Comment by bgreenwell** [comment]
Revised. Probability should not be used in the interpretation of the magnitudes of the coefficients in logistic regression. They should be interpreted in terms of the multiplicative increase to the odds of success per one-unit increase in X, etc.

**Comment by cunningjames** [comment]
#probitnotlogit

**Comment by bgreenwell** [comment]
Probably beyond the scope of this 📖, but you bring up a good point, the link function can be seen as a hyperparameter (unless you have a specific need for one over another). For example, why not use the log-log or complimentary log-log link? In our [sure paper]( https://journal.r-project.org/archive/2018/RJ-2018-004/index.html) we discuss a residual-based approach for assessing the appropriateness of the specified link function. The logit link, while common, is not uniformly the most appropriate. But damn, the probit? What is this, the 1930s? 😉

**Comment by bradleyboehmke** [comment]
Closing this out. @bgreenwell & @cunningjames, we can reopen this up if we feel like we want to address it in the future.
